### ISSUE TITLE
Error generating README

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-tools#357]
I get this error when trying to generate the README for this addon: https://github.com/OCA/l10n-spain/pull/855

```
Traceback (most recent call last):
  File "/usr/local/bin/oca-gen-addon-readme", line 11, in <module>
    load_entry_point('oca-maintainers-tools==0.1.dev816+g1b31efe', 'console_scripts', 'oca-gen-addon-readme')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev816+g1b31efe-py2.7.egg/tools/gen_addon_readme.py", line 200, in gen_addon_readme
    repo_name, branch, addon_name, addon_dir, manifest)
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev816+g1b31efe-py2.7.egg/tools/gen_addon_readme.py", line 147, in gen_one_addon_readme
    runbot_id=runbot_id,
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 12, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

@sbidoul any clue?

**Comment by sbidoul** [comment]
Is it possible one of the fragments or manifest key is not proper utf-8?

**Comment by fuentes010** [comment]
@pedrobaeza this error is because there is a ñ at USAGE.rst
As [Jinja use unicode internally](http://jinja.pocoo.org/docs/2.10/api/#unicode), I guess [here](https://github.com/OCA/maintainer-tools/blob/master/tools/gen_addon_readme.py#L110) the fragment text must be converted to unicode (Haven't tested)

**Comment by sbidoul** [comment]
The code assumes fragments are utf8 and [properly decodes](https://github.com/OCA/maintainer-tools/blob/1b31efe8bf0971445af49eae82eb072d4b1bcf2c/tools/gen_addon_readme.py#L110) them.

It works with python 2 and 3.

It must be something else. Perhaps the manifest?

**Comment by moylop260** [comment]
@pedrobaeza 

Could you try using the following patch?

```patch
diff --git a/l10n_es_aeat_sii/__manifest__.py b/l10n_es_aeat_sii/__manifest__.py
index 3d9a6be7..07a9e973 100644
--- a/l10n_es_aeat_sii/__manifest__.py
+++ b/l10n_es_aeat_sii/__manifest__.py
@@ -10,7 +10,7 @@
 # License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

 {
-    "name": "Suministro Inmediato de Información en el IVA",
+    "name": u"Suministro Inmediato de Información en el IVA",
     "version": "10.0.2.1.5",
     "category": "Accounting & Finance",
     "website": "https://odoospain.odoo.com",
```

**Comment by pedrobaeza** [comment]
That's it, Moi! Thanks. It's my fault.
