### ISSUE TITLE
Unable to generate readme, no rst2html4.py found

### ISSUE THREAD

**Issue by mlaitinen** [OCA/maintainer-tools#369]
### Milestone (Odoo version)
- 11.0

### Module(s)
- server-tools/base_search_fuzzy (I'm not working on it, just testing how the `oca-gen-addon-readme` works)

### Steps to reproduce
1. Install maintainer tools as instructed (I'm running on Ubuntu 18.04, tried both Python 2.7 and Python 3.6.5)
2. Run `python -m tools.gen_addon_readme --repo-name server-tools --branch 11.0 --addon-dir base_search_fuzzy`

### Current behavior
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev839+g9b159bc.d20180828-py2.7.egg/tools/gen_addon_readme.py", line 211, in <module>
    gen_addon_readme()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev839+g9b159bc.d20180828-py2.7.egg/tools/gen_addon_readme.py", line 204, in gen_addon_readme
    repo_name, branch, addon_name, addon_dir, manifest)
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev839+g9b159bc.d20180828-py2.7.egg/tools/gen_addon_readme.py", line 156, in gen_one_addon_readme
    ], stdout=devnull)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

And on the line 156 the script is trying to call `rst2html4.py` but such file can't be found. I can't find it in the PyPi repositories or even Ubuntu repositories. `rst2html5` is available though.

### Expected behavior
The README.rst gets generated

**Comment by mlaitinen** [comment]
I installed `rst2html5` from Ubuntu repositories and checked out the commit before 1ab6dcb612437267bdcfab041d54d3a1662a94b9 and now generating the readme works.

**Comment by sbidoul** [comment]
@mlaitinen this is because the subprocess.call does not find rst2html4 in the path. It is present in the maintainer-tools virtualenv though, since it is provided by docutils.

#370 fixes this.
