### ISSUE TITLE
oca-gen-addon-readme traceback

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-tools#402]
```
fatal: ./../../../dockery-odoo/vendor/OCA/account-financial-tools/account_journal_lock_date/README.rst: './../../../glo/tc-dockery-odoo/vendor/OCA/account-financial-tools/account_journal_lock_date/README.rst' is outside repository
Traceback (most recent call last):
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/bin/oca-gen-addon-readme", line 11, in <module>
    load_entry_point('oca-maintainers-tools==0.1.dev892+gdca05d0', 'console_scripts', 'oca-gen-addon-readme')()
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/lib/python3.6/site-packages/oca_maintainers_tools-0.1.dev892+gdca05d0-py3.6.egg/tools/gen_addon_readme.py", line 318, in gen_addon_readme
    commit_if_needed(readme_filenames, '[UPD] README.rst')
  File "/home/blaggacao/xoe/odoo/OCA/maintainers-tools/env/lib/python3.6/site-packages/oca_maintainers_tools-0.1.dev892+gdca05d0-py3.6.egg/tools/gitutils.py", line 8, in commit_if_needed
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'add', './../../../dockery-odoo/vendor/OCA/account-financial-tools/account_journal_lock_date/README.rst', './../../../dockery-odoo/vendor/OCA/account-financial-tools/account_journal_lock_date/static/description/index.html']' returned non-zero exit status 128.
```

Something is wrong (or incomplete) with the git commit flag... Drop the commit flag all together?

**Comment by pedrobaeza** [comment]
This is probably due to the use of subrepos. Is the case? Use the flag for not committing and include the changes in you migration commit.

**Comment by blaggacao** [comment]
Maybe, another reason could be the relative path `../../../`...

**Comment by pedrobaeza** [comment]
https://github.com/OCA/maintainer-tools/blob/master/tools/gitutils.py#L6

**Comment by blaggacao** [comment]
Yep, without a propper `--git-dir` passed around that would not work except for the being executed in the same repo as the target addons dir. As `--addon-dir` is a multi flag (so you can add any dirs you want across several repos) one way or the other something will break in such cases.

Or this one would need to infer git dirs for the paths that are passed around, group them and do a commit per each repo implied by them: https://github.com/OCA/maintainer-tools/blob/master/tools/gitutils.py#L6

**Comment by pedrobaeza** [comment]
Well, the commit option is intended for the bot to do the work on merges, so sophisticating it can be overkilling IMO.

**Comment by blaggacao** [comment]
Ah ok, then I'll close. Maybe this is something for when this repo might undergo it's first GA version refactoring (that might probably not so soon)...
