### ISSUE TITLE
oca-gen-addon-readme fails with not utf-8 caracter in __manifest__.py

### ISSUE THREAD

**Issue by jobiols** [OCA/maintainer-tools#429]
### Steps to reproduce
1. create a module
2. in __manifest__.py set 'author': "Pelayo Gómez"  note the accentuated ó
3. set # -*- coding: utf-8 -*- at the top 

### Current behavior
when generating the README it fails with

Traceback (most recent call last):
  File "/usr/local/bin/oca-gen-addon-readme", line 11, in <module>
    load_entry_point('oca-maintainers-tools==0.1.dev933+g5dbc863', 'console_scripts', 'oca-gen-addon-readme')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev933+g5dbc863-py2.7.egg/tools/gen_addon_readme.py", line 310, in gen_addon_readme
    org_name, repo_name, branch, addon_name, addon_dir, manifest)
  File "/usr/local/lib/python2.7/dist-packages/oca_maintainers_tools-0.1.dev933+g5dbc863-py2.7.egg/tools/gen_addon_readme.py", line 231, in gen_one_addon_readme
    development_status=development_status,
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 67, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128)

### Expected behavior
the accentuated caracter is handled property and the README is generated.

**Comment by pedrobaeza** [comment]
You have to put `u"Pelayo Gómez"`
