### ISSUE TITLE
15.0 unsupported in pre-commit

### ISSUE THREAD

**Issue by ap-wtioit** [OCA/maintainer-tools#513]
### Milestone (Odoo version)
- 15.0

### Module(s)
- pre-commit

### Steps to reproduce
1. Run pre-commit in a 15.0 branch (e.g. https://github.com/OCA/web/pull/2055/checks?check_run_id=3927439714)

### Current behavior
```
/opt/hostedtoolcache/Python/3.9.7/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files
forbidden files......................................(no files to check)Skipped
Update pre-commit excluded addons........................................Passed
Fix the manifest website key.............................................Passed
autoflake................................................................Passed
black....................................................................Passed
prettier (with plugin-xml)...............................................Passed
eslint...................................................................Passed
- hook id: eslint
- duration: 0.47s
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Xml................................................................Passed
Mixed line ending........................................................Passed
pyupgrade................................................................Passed
isort except __init__.py.................................................Passed
Generate default setup.py for an addons directory........................Failed
- hook id: setuptools-odoo-make-default
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoc0qkxm26/py_env-python3/bin/setuptools-odoo-make-default", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoc0qkxm26/py_env-python3/lib/python3.9/site-packages/setuptools_odoo/make_default_setup.py", line 397, in main
    make_default_setup_addons_dir(
  File "/home/runner/.cache/pre-commit/repoc0qkxm26/py_env-python3/lib/python3.9/site-packages/setuptools_odoo/make_default_setup.py", line 151, in make_default_setup_addons_dir
    make_default_setup_addon(
  File "/home/runner/.cache/pre-commit/repoc0qkxm26/py_env-python3/lib/python3.9/site-packages/setuptools_odoo/make_default_setup.py", line 98, in make_default_setup_addon
    _, _, odoo_version_info = _get_version(
  File "/home/runner/.cache/pre-commit/repoc0qkxm26/py_env-python3/lib/python3.9/site-packages/setuptools_odoo/core.py", line 151, in _get_version
    raise DistutilsSetupError(
distutils.errors.DistutilsSetupError: Unsupported odoo version '15.0' in ./web_environment_ribbon
```

### Expected behavior

Version 15.0 should be supported by now.

Not 100% sure if this belongs to maintainer-tools but i would guess so.

**Comment by ap-wtioit** [comment]
fixed with https://github.com/OCA/oca-addons-repo-template/pull/75
