### ISSUE TITLE
oca-set-repo-labels: Returns a 404 error

### ISSUE THREAD

**Issue by rousseldenis** [OCA/maintainer-tools#543]
`Traceback (most recent call last):
  File "/home/dro-local/.local/bin/oca-set-repo-labels", line 8, in <module>
    sys.exit(main())
  File "/home/dro-local/.local/pipx/venvs/oca-maintainers-tools/lib/python3.10/site-packages/tools/set_repo_labels.py", line 73, in main
    repo_label.update(label_name, label_color, label_description)
  File "/home/dro-local/.local/pipx/venvs/oca-maintainers-tools/lib/python3.10/site-packages/github3/decorators.py", line 24, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/dro-local/.local/pipx/venvs/oca-maintainers-tools/lib/python3.10/site-packages/github3/issues/label.py", line 64, in update
    json = self._json(resp, 200)
  File "/home/dro-local/.local/pipx/venvs/oca-maintainers-tools/lib/python3.10/site-packages/github3/models.py", line 161, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
`

Running it locally showed me it retrieves the .github local directory from the `gh.repositories_by("OCA")` function.

@simahawk @sbidoul

**Comment by rousseldenis** [comment]
Replacing the function to get one repo `gh.repository(owner, repo)` gave me a workaround to fix this

**Comment by rousseldenis** [comment]
Great!
