### ISSUE TITLE
I faced with error while using this module in pre-commit.

### ISSUE THREAD

**Issue by mostafabarmshory** [OCA/maintainer-tools#579]
Here is my pre-commit config (copied from readme)
```python

  - repo: https://github.com/oca/maintainer-tools
    rev: master
    hooks:
      # Use each script's `--help` to understand the args
      - id: oca-gen-addon-readme
        args:
          - --addons-dir=.
          - --org-name=OCA
          - --repo-name=server-tools
          - --branch=13.0

      # This job could easily produce conflicts when it runs on every commit,
      # so it's added as a manual job. If you automate it, beware.
      # See https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
      - id: oca-gen-addons-table
        stages: [manual]

      - id: oca-gen-addon-icon
        args:
          - --addons-dir=.
``` 

I faced an error in executing pre-commit run.

```python

[INFO] Installing environment for https://github.com/oca/maintainer-tools.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /home/maso/.cache/pre-commit/patch1695987386-172290.
An unexpected error has occurred: CalledProcessError: command: ('/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Looking in indexes: http://192.168.88.100:5000/index/
    Processing /home/maso/.cache/pre-commit/repociurf2xt
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [48 lines of output]
          /home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
          !!
          
                  ********************************************************************************
                  Requirements should be satisfied by a PEP 517 installer.
                  If you are using pip, you can try `pip install --use-pep517`.
                  ********************************************************************************
          
          !!
            dist.fetch_build_eggs(dist.setup_requires)
          WARNING: The repository located at 192.168.88.100 is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host 192.168.88.100'.
          ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
          ERROR: No matching distribution found for setuptools_scm
          Traceback (most recent call last):
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
              subprocess.check_call(cmd)
            File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1dqkqhwo', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
          
          The above exception was the direct cause of the following exception:
          
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/home/maso/.cache/pre-commit/repociurf2xt/setup.py", line 11, in <module>
              setuptools.setup(
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/__init__.py", line 106, in setup
              _install_setup_requires(attrs)
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
              _fetch_build_eggs(dist)
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
              dist.fetch_build_eggs(dist.setup_requires)
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
              return _fetch_build_eggs(self, requires)
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
              resolved_dists = pkg_resources.working_set.resolve(
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 827, in resolve
              dist = self._resolve_dist(
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
              dist = best[req.key] = env.best_match(
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1133, in best_match
              return self.obtain(req, installer)
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1145, in obtain
              return installer(requirement)
            File "/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/lib/python3.10/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
              raise DistutilsError(str(e)) from e
          distutils.errors.DistutilsError: Command '['/home/maso/.cache/pre-commit/repociurf2xt/py_env-python3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1dqkqhwo', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /home/maso/.cache/pre-commit/pre-commit.log

```

**Comment by sbidoul** [comment]
This the clue

> Looking in indexes: http://192.168.88.100:5000/index/

You probably have a local pip config that changes the default index.
