### ISSUE TITLE
copy_maintainers script fails syncing the big teams

### ISSUE THREAD

**Issue by hbrunn** [OCA/maintainer-tools#615]
We call `copy_maintainers --team "OCA Contributors"` and `copy_maintainers --team "OCA Members"` daily to update the appropriate teams in github.

Since a while I receive nearly daily mails about one of those failing with a bad gateway error (503). Can just reading this [char field](https://github.com/OCA/maintainer-tools/blob/master/tools/copy_maintainers.py#L199) for a few hundred users really take 10min? (that's the proxy_read_timeout value of the oca nginx server). Or does nginx return 503 for some other reason? Buffer size possibly? I can't check myself because I can't see nginx' error log on the OCA server.

Chunking should help I guess? And if I touch this anyways, are there reservations against using oca's own [odoorpc](https://github.com/OCA/odoorpc/) instead of the unmaintained erppeek?

**Comment by pedrobaeza** [comment]
Is this still in use? @etobella what you did is complementary to this?

**Comment by etobella** [comment]
Well, this is used for Oca contributors team, it is not maintaned there :thinking:

**Comment by hbrunn** [comment]
@pedrobaeza what is what @etobella did that might be complementary? I've never been involved in the housekeeping so much, but it seems if this fails new contributors aren't added to the good github group?

**Comment by sbidoul** [comment]
I just tried to reproduce the team sync error, and... it succeeded, except for a bunch of problems related to invalid GitHub handles in our database. I'll look if the error comes up again.

**Comment by hbrunn** [comment]
yesterday night it failed because of the rate limit, I assume that's because you used the gitbot user's token for your tests?

You receive the error messages per mail too, right?

Not sure how to continue here. Should we just accept this to fail sometimes? Is this a timing issue and we possibly just need to spread out the heavy scripts in time more?

**Comment by sbidoul** [comment]
We probably need to add a retry mechanism on GitHub operations in copy_maintainers.py. This is low priority for me, but if I was to do it I'd try with tenacity or stamina.

**Comment by sbidoul** [comment]
Here is a recent stack trace of it reaching the API rate limits:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/copy-maintainers/maintainer-tools/tools/copy_maintainers.py", line 261, in <module>
    main()
  File "/home/copy-maintainers/maintainer-tools/tools/copy_maintainers.py", line 257, in main
    copy_users(odoo, team=args.team, dry_run=args.dry_run)
  File "/home/copy-maintainers/maintainer-tools/tools/copy_maintainers.py", line 166, in copy_users
    github_teams = GHTeamList(gh, org="oca", dry_run=dry_run)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/copy-maintainers/maintainer-tools/tools/copy_maintainers.py", line 60, in __init__
    self._org = self._gh.organization("oca")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/copy-maintainers/venv/lib/python3.11/site-packages/github3/github.py", line 1688, in organization
    json = self._json(self._get(url), 200)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/copy-maintainers/venv/lib/python3.11/site-packages/github3/models.py", line 161, in _json
    raise exceptions.error_for(response)
github3.exceptions.ForbiddenError: 403 API rate limit exceeded for user ID 8723280. If you reach out to GitHub Support for help, please include the request ID DF04:195265:3244A37:2C3A1A9:6966A442 and timestamp 2026-01-13 20:00:02 UTC. For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service)
```

Not sure if the problem is from this script specifically or the oca-git-bot account globally.
